### ISSUE TITLE
Sending single word to channel / privmsg throws error

### ISSUE THREAD

**Issue by mihav** [insomniacslk/irc-slack#76]
When I'm trying to send single word/url to user or to channel, message is not relayed and console log throws "Invalid PRIVMSG command args" error:

2019/12/10 09:51:01 127.0.0.1:51172: PRIVMSG user https://github.com/insomniacslk/irc-slack/issues
2019/12/10 09:51:01 Invalid PRIVMSG command args: [user https://github.com/insomniacslk/irc-slack/issues]
2019/12/10 09:51:01 Got new message {@user  }

The moment I append whitespace at the end it gets through:
2019/12/10 09:51:09 127.0.0.1:51172: PRIVMSG user :https://github.com/insomniacslk/irc-slack/issues .                                                                                                                                         
2019/12/10 09:51:09 Got new message {@user  https://github.com/insomniacslk/irc-slack/issues .}

**Comment by insomniacslk** [comment]
hi @mihav , I am finally catching up with issues here, apologies for the delay! I'll work on this one today, thanks for reporting it :)

**Comment by insomniacslk** [comment]
@mihav I'm not able to reproduce the issue here, I've just sent a single-word message to a channel and to an user without problems, and I see the message relayed and showing up correctly. Same thing if I send an URL as only message.
I can imagine of two things:
* your irc-slack checkout is outdated: easy fix, just git pull and re-run
* your IRC client may do something we don't handle. In which case, if the above test doesn't help, can you let me know which IRC client and version you're using, and which commit hash of irc-slack are you running on?

**Comment by mihav** [comment]
I'm running commit b53c50e6b9510bae8ae472eac7a49fd1e83492a5 from Nov 19.
As for client, I'm using quassel daemon/server combination (version 0.13.1). There is nothing is its debug log though.

I'll update build tomorrow and retry, maybe even with some other IRC client.

**Comment by janza** [comment]
@mihav can you try using the patch in #84, I believe that should fix your issue.

**Comment by mihav** [comment]
Works with your patch. Thanks.

**Comment by insomniacslk** [comment]
Thanks both for debugging and fixing this!
